use_frameworks!

platform :ios, '8.0'

target 'Reader_Example' do
  pod 'Reader', :path => '../'

  target 'Reader_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
